name: alzcare
description: Compassionate Care for Alzheimer's Patients
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # youtube_player_flutter: ^8.1.2
  youtube_player_iframe: ^5.0.0

  

  # UI Components
  cupertino_icons: ^1.0.6

  # State Management
  provider: ^6.1.1

  # Icons
  font_awesome_flutter: ^10.6.0


  intl: ^0.19.0
  emoji_picker_flutter: ^2.2.0
  sqflite: ^2.3.0          
  path_provider: ^2.1.1    
  # image_picker: ^1.0.7     
  path: ^1.8.3

  # Navigation
  go_router: ^12.1.3

  # HTTP & API
  http: ^1.1.2

  # Local Storage
  shared_preferences: ^2.2.2

  flutter_local_notifications: ^17.1.2

  # Image handling
  cached_network_image: ^3.3.1

  # Charts
  fl_chart: ^0.65.0

  # Maps & Location
  url_launcher: ^6.3.0
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  google_maps_flutter: ^2.5.0
  image_picker: ^1.2.0
  video_player: ^2.10.0
  share_plus: 10.0.0




  # speech_to_text: ^6.5.0
  # flutter_tts: ^3.8.5 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  # assets:
  #   - images/
  # fonts:
  #   - family: Custom
  #     fonts:
  #       - asset: fonts/Custom-Regular.ttf